# -*- coding: utf-8 -*-
"""Data_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/185TSNNBmY-ecFfopCSrNe584nJogIE6H
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""library numpy =>Olah numberik di pyton"""

dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

print(y)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainer='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

from sklearn preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0,2, random_state = 1)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

print(x_train)

print(x_test)