# -*- coding: utf-8 -*-
"""Apriori

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CcE6qAnL1SFqdq9vX3QMYHkt7m4-CFZ1
"""

import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_excel('Online_Retail_ind.xlsx')
data.head()

data.columns

data.T1.unique()

data['T1'] = data['T1'].str.strip()
data.dropna(axis = 0, subset =['T2'], inplace = True)
data['T2'] = data['T2'].astype('str')
data = data[~data['InvoiceNo'].str.contains('C')]

def hot_encode(x):
    if(x<= 0):
        return 0
    if(x>= 1):
        return 1

basket_encoded = basket_Roti.applymap(hot_encode)
basket_Roti = basket_encoded
  
basket_encoded = basket_Selai.applymap(hot_encode)
basket_Selai = basket_encoded
  
basket_encoded = basket_Mentega.applymap(hot_encode)
basket_Mentega = basket_encoded
  
basket_encoded = basket_Susu.applymap(hot_encode)
basket_Susu = basket_encoded

basket_encoded = basket_Cokelat.applymap(hot_encode)
basket_Cokelat = basket_encoded

frq_items = apriori(basket_Roti, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())

frq_items = apriori(basket_Selai, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())

frq_items = apriori(basket_Mentega, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())

frq_items = apriori(basket_Selai, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())

frq_items = apriori(basket_Susu, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())

frq_items = apriori(basket_Cokelat, min_support = 0.3, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
print(rules.head())