# -*- coding: utf-8 -*-
"""Tugas_Besar_Data-Mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lw3Y1s8bBWYq378hM9OW-_XxrF-Vmmnt
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

col_names = ['ID_KEL', 'Nama_kota', 'Nama_kecamatan', 'SUSPEK' , 'Perawatan' , 'POSITIF' , 'Sembuh' , 'Meninggal']
pima = pd.read_csv("Data_Covid-19_DKI_Jakarta.csv", header=None, names=col_names)

pima.head()

feature_cols = ['ID_KEL', 'Nama_kota', 'Nama_kecamatan', 'SUSPEK' , 'Perawatan' , 'POSITIF' , 'Sembuh' , 'Meninggal']
X = pima[feature_cols] 
y = pima.label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

clf = DecisionTreeClassifier()

clf = clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('diabetes.png')
Image(graph.create_png())